apiVersion: v2
name: simple-web-api
icon: https://s3-us-west-2.amazonaws.com/s.cdpn.io/49212/Icon-Small%403x.png
description: An Helm chart to test deployment and various concept in rust
type: application
sources:
  - https://gitlab-gxp.cloud.health.ge.com/100026625/sandbox
version: 0.7.8
appVersion: 1.18.2
kubeVersion: "1.31.2"
annotations:
  extensionVersion: 0.0.1
  category: Infrastructure
  images: |
    - name: simple-web-api
      image: zot.if.local/blaurent/simple-web-api:1.18.6
  gehealthcare.com/requires: |
    - name: doom-web-api
      type: helm
      version: "~0.2.0"
    - name: flask-web-api
      type: "service"
      version: "0.0.1"
dependencies:
  - condition: nats.enabled
    name: nats
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 8.x.x
  - condition: echo.enabled
    name: echo-web-api
    repository: oci://registry-1.docker.io/blaurent
    version: 0.7.x
  - condition: wordpress.enabled
    name: wordpress
    repository: https://charts.bitnami.com/bitnami
    version: 22.x.x
