commonSettings:
  image:
    registryUrl: zot.if.local
    pullPolicy: Always
    repository: blaurent
  ingress: true
  podLabels: {}
simpleWebApi:
  env:
    NB_WORKERS: 2
  replicaCount: 2
  image:
    repository: zot.if.local/blaurent/simple-web-api
    tag: 1.18.1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
nats:
  enabled: true
echo:
  enabled: true
wordpress:
  enabled: true
