apiVersion: v2
name: echo-web-api
icon: https://s3-us-west-2.amazonaws.com/s.cdpn.io/49212/Icon-Small%403x.png
description: An Helm chart to test deployment and various concept in python
type: application
version: 0.7.4
appVersion: 1.6.1
annotations:
  extensionVersion: 0.0.1
  category: Infrastructure
  images: |
    - name: echo-web-api
      image: blaurent/echo-web-api:1.6.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.4.x
