apiVersion: v2
name: echo-web-api
icon: https://s3-us-west-2.amazonaws.com/s.cdpn.io/49212/Icon-Small%403x.png
description: An Helm chart to test deployment and various concept in python
type: application
sources:
- https://gitlab-gxp.cloud.health.ge.com/100026625/sandbox
version: 0.7.8
appVersion: 1.6.2
kubeVersion: 1.30.2
annotations:
  extensionVersion: 0.0.1
  category: Infrastructure
  images: |
    - name: echo-web-api
      image: zot.if.local/blaurent/echo-web-api:1.6.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.4.x
