apiVersion: v2
name: echo-web-api
icon: https://s3-us-west-2.amazonaws.com/s.cdpn.io/49212/Icon-Small%403x.png
description: An Helm chart to test deployment and various concept in python
type: application
version: 0.2.0
appVersion: v1.6.0
annotations:
  extension_version: 0.0.1
  category: Infrastructure
  images: |
    - name: echo-web-api
      image: blaurent/echo-web-api:v1.6.0
  env: |
    - name: NB_WORKERS
      value: 4 
      description: "Set the number of workers to be used."
dependencies:
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.4.x
