commonSettings:
  image:
    registryUrl: zot.if.local
    pullPolicy: Always
    repository: blaurent
  ingress: true
  podLabels: {}
  annotations:
    version: 1.6.0
echoWebApi:
  replicaCount: 2
  NB_WORKERS: 2
  image:
    repository: zot.if.local/blaurent/echo-web-api
    tag: 1.6.1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
redis:
  enabled: true
